# Configuration for https://probot.github.io/apps/auto-assign

addReviewers: true
addAssignees: false

reviewers: 
  - sohkai
  - 0x6431346e

skipKeywords:
  - wip
  - draft

# Set 0 to add all the reviewers (default: 0)
numberOfReviewers: 0
