os: osx
osx_image: xcode9.4
language: node_js
node_js: "10"
env:
  - ELECTRON_CACHE=$HOME/.cache/electron
  - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

script:
  - ./bin/build

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"